# Generated by Django 6.0.6 on 2026-06-26 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='total_seats',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='source',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='route',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='bus',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.CharField(default='chennai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='origin',
            field=models.CharField(default='madurai', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.IntegerField(default='500'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('seat_number', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bus')),
            ],
        ),
    ]
